FROM ghcr.io/owl-corp/python-poetry-base:3-slim

# Install project dependencies
WORKDIR /my-app
COPY pyproject.toml poetry.lock ./
RUN poetry install

# Copy the source code in last to optimize rebuilding the image
COPY . .

ENTRYPOINT ["poetry", "run"]
CMD ["python", "-m", "app"]
